# Generated by Django 5.2 on 2025-04-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
    ]
