# Generated by Django 5.2 on 2025-04-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_meal_id_alter_rating_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default=None, upload_to='meal_images'),
            preserve_default=False,
        ),
    ]
